### ISSUE TITLE
bug in subparts

### ISSUE THREAD

**Issue by unknowndunkan** [fxwei/DSE-Style-Template#1]
When adding third `subpart`, margin between the `\subpart` label and the text make the paragraph not justified.

![image](https://user-images.githubusercontent.com/73874075/200830583-726fcf83-5c7f-4b78-a6d0-6c9c082ad7c2.png)

**Comment by fxwei** [comment]
> When adding third `subpart`, margin between the `\subpart` label and the text make the paragraph not justified.
> 
> ![image](https://user-images.githubusercontent.com/73874075/200830583-726fcf83-5c7f-4b78-a6d0-6c9c082ad7c2.png)
> 

Noted. As I am a bit busy in these days, let me look into the issue and see if I can address by this weekend. Thanks for report

## \*Update\*
Thanks again for the report. You may try to play around with `\renewcommand\subpartshook` to adjust the indentations or spacings etc. I replaced the relevant codes with the following:
```
\renewcommand\questionshook{
    \setlength{\labelsep}{16pt}
    \setlength{\leftmargin}{16pt}
}
\renewcommand\partshook{
    \setlength{\labelsep}{22pt}
    \setlength{\leftmargin}{34pt}
}
\renewcommand\subpartshook{
    \renewcommand\makelabel[1]{##1\hfil }
    \setlength{\labelwidth}{\labelsep}
    \setlength{\labelsep}{12pt}
    \setlength{\leftmargin}{34pt}
}
```
which works for me.
![image](https://user-images.githubusercontent.com/86094248/200994919-eeee1a6d-a8a5-4ff9-9b8f-1e3fae3c0cdc.png)
